/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TaskEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_DISPUTE_WINDOW"
      | "MIN_AMOUNT"
      | "complete"
      | "confirm"
      | "deposit"
      | "depositWithWindow"
      | "getTask"
      | "owner"
      | "refund"
      | "reject"
      | "releaseAfterDispute"
      | "tasks"
      | "transferOwnership"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Completed"
      | "Deposited"
      | "OwnerChanged"
      | "Refunded"
      | "Rejected"
      | "Released"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "complete", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "confirm", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWithWindow",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getTask", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "refund", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "reject", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "releaseAfterDispute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_AMOUNT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "complete", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "confirm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositWithWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseAfterDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace CompletedEvent {
  export type InputTuple = [taskId: BytesLike, disputeDeadline: BigNumberish];
  export type OutputTuple = [taskId: string, disputeDeadline: bigint];
  export interface OutputObject {
    taskId: string;
    disputeDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    buyer: AddressLike,
    seller: AddressLike,
    amount: BigNumberish,
    slaDeadline: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    buyer: string,
    seller: string,
    amount: bigint,
    slaDeadline: bigint
  ];
  export interface OutputObject {
    taskId: string;
    buyer: string;
    seller: string;
    amount: bigint;
    slaDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerChangedEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: string, buyer: string, amount: bigint];
  export interface OutputObject {
    taskId: string;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RejectedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: string, buyer: string, amount: bigint];
  export interface OutputObject {
    taskId: string;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleasedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    seller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: string, seller: string, amount: bigint];
  export interface OutputObject {
    taskId: string;
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): TaskEscrow;
  waitForDeployment(): Promise<this>;

  interface: TaskEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  MIN_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  complete: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  confirm: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  deposit: TypedContractMethod<
    [
      taskId: BytesLike,
      seller: AddressLike,
      amount: BigNumberish,
      slaDeadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  depositWithWindow: TypedContractMethod<
    [
      taskId: BytesLike,
      seller: AddressLike,
      amount: BigNumberish,
      slaDeadline: BigNumberish,
      disputeWindow: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getTask: TypedContractMethod<
    [taskId: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        buyer: string;
        seller: string;
        amount: bigint;
        slaDeadline: bigint;
        disputeDeadline: bigint;
        disputeWindow: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  reject: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  releaseAfterDispute: TypedContractMethod<
    [taskId: BytesLike],
    [void],
    "nonpayable"
  >;

  tasks: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        buyer: string;
        seller: string;
        amount: bigint;
        slaDeadline: bigint;
        disputeDeadline: bigint;
        disputeWindow: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "complete"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirm"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      seller: AddressLike,
      amount: BigNumberish,
      slaDeadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositWithWindow"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      seller: AddressLike,
      amount: BigNumberish,
      slaDeadline: BigNumberish,
      disputeWindow: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        buyer: string;
        seller: string;
        amount: bigint;
        slaDeadline: bigint;
        disputeDeadline: bigint;
        disputeWindow: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reject"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseAfterDispute"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        buyer: string;
        seller: string;
        amount: bigint;
        slaDeadline: bigint;
        disputeDeadline: bigint;
        disputeWindow: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Completed"
  ): TypedContractEvent<
    CompletedEvent.InputTuple,
    CompletedEvent.OutputTuple,
    CompletedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerChanged"
  ): TypedContractEvent<
    OwnerChangedEvent.InputTuple,
    OwnerChangedEvent.OutputTuple,
    OwnerChangedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "Rejected"
  ): TypedContractEvent<
    RejectedEvent.InputTuple,
    RejectedEvent.OutputTuple,
    RejectedEvent.OutputObject
  >;
  getEvent(
    key: "Released"
  ): TypedContractEvent<
    ReleasedEvent.InputTuple,
    ReleasedEvent.OutputTuple,
    ReleasedEvent.OutputObject
  >;

  filters: {
    "Completed(bytes32,uint256)": TypedContractEvent<
      CompletedEvent.InputTuple,
      CompletedEvent.OutputTuple,
      CompletedEvent.OutputObject
    >;
    Completed: TypedContractEvent<
      CompletedEvent.InputTuple,
      CompletedEvent.OutputTuple,
      CompletedEvent.OutputObject
    >;

    "Deposited(bytes32,address,address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "OwnerChanged(address,address)": TypedContractEvent<
      OwnerChangedEvent.InputTuple,
      OwnerChangedEvent.OutputTuple,
      OwnerChangedEvent.OutputObject
    >;
    OwnerChanged: TypedContractEvent<
      OwnerChangedEvent.InputTuple,
      OwnerChangedEvent.OutputTuple,
      OwnerChangedEvent.OutputObject
    >;

    "Refunded(bytes32,address,uint256)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "Rejected(bytes32,address,uint256)": TypedContractEvent<
      RejectedEvent.InputTuple,
      RejectedEvent.OutputTuple,
      RejectedEvent.OutputObject
    >;
    Rejected: TypedContractEvent<
      RejectedEvent.InputTuple,
      RejectedEvent.OutputTuple,
      RejectedEvent.OutputObject
    >;

    "Released(bytes32,address,uint256)": TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
    Released: TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
  };
}
